apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      securityContext:
        fsGroup: 999
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-secret
          args:
            - -c
            - ssl=on
            - -c
            - ssl_cert_file=/etc/postgres-tls/server.crt
            - -c
            - ssl_key_file=/etc/postgres-tls/server.key
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
            - name: tls
              mountPath: /etc/postgres-tls
              readOnly: true
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
        - name: tls
          secret:
            secretName: postgres-tls
            defaultMode: 0640
